### PR TITLE
Select User for Chat Functionality

### PR DESCRIPTION
**Pull request by idoko-emmanuel**
### Description:
This pull request implements the "Select User for Chat" feature, which allows users to choose a specific user to start a conversation with in the chat interface.

### CODE REVIEW

**Comment by peculiaruc** [comment]
Is there any reason you closed this PR @idoko-emmanuel ?

**Comment by idoko-emmanuel** [comment]
Yes, I mistakenly created the pull request on the main branch instead of the develop branch. To ensure proper code review and adherence to our development workflow, I closed the pull request. I created a new pull request targeting the develop branch to maintain the correct branching strategy and code integration process. @peculiaruc

**Comment by idoko-emmanuel** [comment]
Yes, I mistakenly created the pull request on the main branch instead of
the develop branch. To ensure proper code review and adherence to our
development workflow, I closed the pull request. I created a new pull
request targeting the develop branch to maintain the correct branching
strategy and code integration process.

**Comment by peculiaruc** [comment]
I see. Well done.

**Comment by idoko-emmanuel** [comment]
Thank you

**Pull request closed without merging**
